// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.usyd.group7.domain;

import com.usyd.group7.domain.ClientLevel;
import com.usyd.group7.domain.ClientLevelDataOnDemand;
import com.usyd.group7.domain.ClientLevelIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClientLevelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClientLevelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClientLevelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClientLevelIntegrationTest: @Transactional;
    
    @Autowired
    ClientLevelDataOnDemand ClientLevelIntegrationTest.dod;
    
    @Test
    public void ClientLevelIntegrationTest.testCountClientLevels() {
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", dod.getRandomClientLevel());
        long count = ClientLevel.countClientLevels();
        Assert.assertTrue("Counter for 'ClientLevel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClientLevelIntegrationTest.testFindClientLevel() {
        ClientLevel obj = dod.getRandomClientLevel();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to provide an identifier", id);
        obj = ClientLevel.findClientLevel(id);
        Assert.assertNotNull("Find method for 'ClientLevel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClientLevel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClientLevelIntegrationTest.testFindAllClientLevels() {
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", dod.getRandomClientLevel());
        long count = ClientLevel.countClientLevels();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClientLevel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClientLevel> result = ClientLevel.findAllClientLevels();
        Assert.assertNotNull("Find all method for 'ClientLevel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClientLevel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClientLevelIntegrationTest.testFindClientLevelEntries() {
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", dod.getRandomClientLevel());
        long count = ClientLevel.countClientLevels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClientLevel> result = ClientLevel.findClientLevelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClientLevel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClientLevel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClientLevelIntegrationTest.testFlush() {
        ClientLevel obj = dod.getRandomClientLevel();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to provide an identifier", id);
        obj = ClientLevel.findClientLevel(id);
        Assert.assertNotNull("Find method for 'ClientLevel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClientLevel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ClientLevel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientLevelIntegrationTest.testMergeUpdate() {
        ClientLevel obj = dod.getRandomClientLevel();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to provide an identifier", id);
        obj = ClientLevel.findClientLevel(id);
        boolean modified =  dod.modifyClientLevel(obj);
        Integer currentVersion = obj.getVersion();
        ClientLevel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClientLevel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientLevelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", dod.getRandomClientLevel());
        ClientLevel obj = dod.getNewTransientClientLevel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClientLevel' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ClientLevel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClientLevelIntegrationTest.testRemove() {
        ClientLevel obj = dod.getRandomClientLevel();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClientLevel' failed to provide an identifier", id);
        obj = ClientLevel.findClientLevel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ClientLevel' with identifier '" + id + "'", ClientLevel.findClientLevel(id));
    }
    
}
