// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.usyd.group7.domain;

import com.usyd.group7.domain.ExerciseTypeDataOnDemand;
import com.usyd.group7.domain.ExerciseTypeIntegrationTest;
import com.usyd.group7.service.ExerciseTypeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExerciseTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExerciseTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExerciseTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExerciseTypeIntegrationTest: @Transactional;
    
    @Autowired
    ExerciseTypeDataOnDemand ExerciseTypeIntegrationTest.dod;
    
    @Autowired
    ExerciseTypeService ExerciseTypeIntegrationTest.exerciseTypeService;
    
    @Test
    public void ExerciseTypeIntegrationTest.testCountAllExerciseTypes() {
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", dod.getRandomExerciseType());
        long count = exerciseTypeService.countAllExerciseTypes();
        Assert.assertTrue("Counter for 'ExerciseType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testFindExerciseType() {
        ExerciseType obj = dod.getRandomExerciseType();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to provide an identifier", id);
        obj = exerciseTypeService.findExerciseType(id);
        Assert.assertNotNull("Find method for 'ExerciseType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExerciseType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testFindAllExerciseTypes() {
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", dod.getRandomExerciseType());
        long count = exerciseTypeService.countAllExerciseTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExerciseType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExerciseType> result = exerciseTypeService.findAllExerciseTypes();
        Assert.assertNotNull("Find all method for 'ExerciseType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExerciseType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testFindExerciseTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", dod.getRandomExerciseType());
        long count = exerciseTypeService.countAllExerciseTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExerciseType> result = exerciseTypeService.findExerciseTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ExerciseType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExerciseType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testFlush() {
        ExerciseType obj = dod.getRandomExerciseType();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to provide an identifier", id);
        obj = exerciseTypeService.findExerciseType(id);
        Assert.assertNotNull("Find method for 'ExerciseType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExerciseType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ExerciseType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testUpdateExerciseTypeUpdate() {
        ExerciseType obj = dod.getRandomExerciseType();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to provide an identifier", id);
        obj = exerciseTypeService.findExerciseType(id);
        boolean modified =  dod.modifyExerciseType(obj);
        Integer currentVersion = obj.getVersion();
        ExerciseType merged = exerciseTypeService.updateExerciseType(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ExerciseType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testSaveExerciseType() {
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", dod.getRandomExerciseType());
        ExerciseType obj = dod.getNewTransientExerciseType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExerciseType' identifier to be null", obj.getId());
        try {
            exerciseTypeService.saveExerciseType(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ExerciseType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExerciseTypeIntegrationTest.testDeleteExerciseType() {
        ExerciseType obj = dod.getRandomExerciseType();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExerciseType' failed to provide an identifier", id);
        obj = exerciseTypeService.findExerciseType(id);
        exerciseTypeService.deleteExerciseType(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'ExerciseType' with identifier '" + id + "'", exerciseTypeService.findExerciseType(id));
    }
    
}
