// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.usyd.group7.domain;

import com.usyd.group7.domain.ExerciseType;
import com.usyd.group7.domain.ExerciseTypeDataOnDemand;
import com.usyd.group7.service.ExerciseTypeService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExerciseTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExerciseTypeDataOnDemand: @Component;
    
    private Random ExerciseTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ExerciseType> ExerciseTypeDataOnDemand.data;
    
    @Autowired
    ExerciseTypeService ExerciseTypeDataOnDemand.exerciseTypeService;
    
    public ExerciseType ExerciseTypeDataOnDemand.getNewTransientExerciseType(int index) {
        ExerciseType obj = new ExerciseType();
        setCalorieRate(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ExerciseTypeDataOnDemand.setCalorieRate(ExerciseType obj, int index) {
        double calorieRate = new Integer(index).doubleValue();
        obj.setCalorieRate(calorieRate);
    }
    
    public void ExerciseTypeDataOnDemand.setName(ExerciseType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ExerciseType ExerciseTypeDataOnDemand.getSpecificExerciseType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ExerciseType obj = data.get(index);
        Long id = obj.getId();
        return exerciseTypeService.findExerciseType(id);
    }
    
    public ExerciseType ExerciseTypeDataOnDemand.getRandomExerciseType() {
        init();
        ExerciseType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return exerciseTypeService.findExerciseType(id);
    }
    
    public boolean ExerciseTypeDataOnDemand.modifyExerciseType(ExerciseType obj) {
        return false;
    }
    
    public void ExerciseTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = exerciseTypeService.findExerciseTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ExerciseType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ExerciseType>();
        for (int i = 0; i < 10; i++) {
            ExerciseType obj = getNewTransientExerciseType(i);
            try {
                exerciseTypeService.saveExerciseType(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
