// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.usyd.group7.domain;

import com.usyd.group7.domain.ClientLevel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClientLevel_Roo_Configurable {
    
    declare @type: ClientLevel: @Configurable;
    
}
